### ISSUE TITLE
 uncaughtException: Cannot set property 'readyState' of undefined

### ISSUE THREAD

**Issue by Dominic12** [typestack/socket-controllers#31]
Hi, 

I'm using the function useSocketController but a reload causes the whole node server to crash with the following stack trace.

TypeError: Cannot set property 'readyState' of undefined
at Socket.socketOnClose (/Users/Documents/dev-backend/node_modules/ws/lib/websocket.js:838:24)
at Socket.emit (events.js:203:15)
at Socket.EventEmitter.emit (domain.js:448:20)
at TCP._handle.close (net.js:607:12) {"error":{},"stack":"TypeError: Cannot set property 'readyState' of undefined\n at Socket.socketOnClose (/Users/Documents/dev-backend/node_modules/ws/lib/websocket.js:838:24)\n at Socket.emit (events.js:203:15)\n at Socket.EventEmitter.emit (domain.js:448:20)\n at TCP._handle.close (net.js:607:12)","exception":true,"date":"Tue Apr 14 2020 16:36:31 GMT+0200 (Central European Summer Time)","process":{"pid":18351,"uid":501,"gid":20,"cwd":"/Users/dominicjarmann/Documents/dev-backend","execPath":"/usr/local/Cellar/node@10/10.18.1/bin/node","version":"v10.18.1","argv":["/usr/local/Cellar/node@10/10.18.1/bin/node","/Users/dominicjarmann/Documents/dev-backend/src/app.ts"],"memoryUsage":{"rss":150470656,"heapTotal":73293824,"heapUsed":65529288,"external":319772}},"os":{"loadavg":[2.2626953125,2.5400390625,2.47509765625],"uptime":30616},"trace":[{"column":24,"file":"/Users/dominicjarmann/Documents/dev-backend/node_modules/ws/lib/websocket.js","function":"Socket.socketOnClose","line":838,"method":"socketOnClose","native":false},{"column":15,"file":"events.js","function":"Socket.emit","line":203,"method":"emit","native":false},{"column":20,"file":"domain.js","function":"Socket.EventEmitter.emit","line":448,"method":"emit","native":false},{"column":12,"file":"net.js","function":"TCP._handle.close","line":607,"method":"close","native":false}]}

Here is the code i'm using (beware, i'm copying snippets together for better readability):

`
 const expressApp: Application = createExpressServer({

            cors: {
                origin: (origin, callback) => {
                    if (corsWhitelist.indexOf(origin) !== -1) {
                        callback(undefined, true);
                    } else {
                        callback(new Error('CORS FAILED'));
                    }
                },
            },
            classTransformer: true,
            routePrefix: env.app.routePrefix,
            defaultErrorHandler: false,
      
            controllers: env.app.dirs.controllers,
            middlewares: env.app.dirs.middlewares,
            interceptors: env.app.dirs.interceptors,

            /**
             * Authorization features
             */
            authorizationChecker: authorizationChecker(connection),
            currentUserChecker: currentUserChecker(connection),
        });

    const server = expressApp.listen(env.app.port);
    const io = require('socket.io')(server);

    useSocketServer(io, {
        controllers: env.app.dirs.controllers,
        middlewares: env.app.dirs.middlewares,
    });
`

I've created two issues in related repos: [WS](https://github.com/websockets/ws/issues/1737) and [Socket.IO Engine](https://github.com/socketio/engine.io/issues/600#issuecomment-613481971).

Is there anything wrong with my setup?

By the way: On the client i configure socket.io as follows.

```
const config: SocketIoConfig = { url: environment.websocketServer, options: {
  transports: ['websocket']
  }};
```

If i remove the transports ['websocket'] part, everything works perfectly.

**Comment by Dominic12** [comment]
Discussion is continued in the Socket.IO Issue.
